from django.contrib import admin
from django.urls import path
from bidzOn.views import RegisterAndSendOTP, VerifyOTPAPIView, SignupView, LoginView, UpdatePasswordView, SelectLocationView, ride_request_view, get_ride_details, create_driver, find_driver, get_driver_details, accept_ride, calculate_time, calculate_time1, write_review, driver_reviews, verify_payment, DriverRegisterAndSendOTP, DriverVerifyOTPAPIView, driverSignupView1, driverSignupView2, driverSignupView3, AdminView, AdminLoginView, AdminUpdateView, PendingDriversView, DriverActivationView, CustomDriverLoginView, CustomDriverLocationView, GetRequestIDView, AcceptRequestView, check_request_status, driver_calculate_time, check_user_location, driver_destination_calculate_time, total_users, total_drivers, total_request_ids, total_model_names, get_all_reviews, get_total_request_ids

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sendotp/', RegisterAndSendOTP.as_view()),
    path('verifyotp/', VerifyOTPAPIView.as_view()),
    path('signup/', SignupView.as_view()),
    path('login/', LoginView.as_view()),
    path('forgotpassword/', UpdatePasswordView.as_view()),
    path('selectlocation/', SelectLocationView.as_view()),
    path('riderequest/', ride_request_view),
    path('ridedetails/', get_ride_details),
    path('createdrivers/', create_driver),
    path('finddrivers/', find_driver),
    path('driverdetails/', get_driver_details),
    path('acceptride/', accept_ride),
    path('time/', calculate_time),
    path('time1/', calculate_time1),
    path('review/', write_review),
    path('getreview/', driver_reviews),
    path('verifypayment/', verify_payment),
    path('driversendotp/', DriverRegisterAndSendOTP.as_view()),
    path('driververifyotp/', DriverVerifyOTPAPIView.as_view()),
    path('signupform1/', driverSignupView1.as_view()),
    path('signupform2/', driverSignupView2.as_view()),
    path('signupform3/', driverSignupView3.as_view()),
    path('driverlogin/', CustomDriverLoginView.as_view()),
    path('driverselectlocation/', CustomDriverLocationView.as_view()),
    path('getrequestid/', GetRequestIDView.as_view()),
    path('driveraccept/', AcceptRequestView.as_view()),
    path('drivernoti/', check_request_status),
    path('drivertime/', driver_calculate_time),
    path('checkuser/', check_user_location),
    path('destinationcalculation/', driver_destination_calculate_time),
    path('admin1/', AdminView.as_view()),
    path('adminlogin/', AdminLoginView.as_view()),
    path('adminupdate/', AdminUpdateView.as_view()),
    path('getdrivers/', PendingDriversView.as_view()),
    path('activatedrivers/', DriverActivationView.as_view()),
    path('totalcustomers/', total_users),
    path('totaldrivers/', total_drivers),
    path('totalbookings/', total_request_ids),
    path('totalvehicles/', total_model_names),
    path('getreviews/', get_all_reviews),
    path('route/', get_total_request_ids),
]
