# Generated by Django 4.2 on 2023-04-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidzOn', '0002_intercity_ride_customuser_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercityrequest',
            name='ride_distance',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='ride_distance',
        ),
    ]
